sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - vnc4server
      - xfonts-base

# command to install dependencies
install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.6" ]]; then pip install -r requirements-2.6-dev.txt; else pip install -r requirements-dev.txt; fi

# command to run tests
script: nosetests tests/unit
